version: '3.8'

services:
  typeahead-app:
    container_name: typeahead-system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
